'use client';

import { useEffect, useState } from 'react';

type LabState = Record<string, string | number | string[]>;
const labCopy: Record<string, { tag:string; title:string; intro:string; transfer:string }> = {
  werkstatt:{tag:'ERKENNTNISGRENZEN',title:'Was weisst du – und was vermutest du nur?',intro:'Nimm eine Frage, bei der du gern Gewissheit hättest. Trenne gesichertes Wissen, begründete Vermutung und das, was vorerst offenbleibt.',transfer:'Faust behauptet, trotz seiner Studien nichts sicher zu wissen. Prüfe in „Nacht“, ob er eine methodische Grenze beschreibt oder aus Enttäuschung übertreibt.'},
  krise:{tag:'METHODE UND ERFAHRUNG',title:'Wie entsteht verlässliches Wissen?',intro:'Bücher, Messungen und eigene Erfahrungen liefern unterschiedliche Arten von Einsicht. Halte fest, was jede davon leisten kann – und was nicht.',transfer:'Vergleiche deine Kriterien mit Fausts und Wagners gegensätzlichem Verhältnis zu Studium, Überlieferung und Erfahrung.'},
  natur:{tag:'BEOBACHTUNG UND DEUTUNG',title:'Siehst du – oder deutest du schon?',intro:'Lege das Smartphone für 60 Sekunden mit dem Display nach unten. Beobachte einen Gegenstand und halte nur fest, was wirklich wahrnehmbar ist.',transfer:'Prüfe anschliessend: An welcher Stelle wurde aus einer Beobachtung eine Erklärung? Genau diese Grenze ist für wissenschaftliches Arbeiten entscheidend.'},
  philosophie:{tag:'SPRACHE UND SINN',title:'Welche Übersetzung überzeugt dich?',intro:'Faust prüft nacheinander Wort, Sinn, Kraft und Tat. Ordne die vier Begriffe und begründe deine Wahl an einer konkreten Entscheidung.',transfer:'Vergleiche deine Reihenfolge mit Fausts Übersetzung des Johannes-Prologs. Was gewinnt seine Entscheidung für die „Tat“ – und was verliert sie?'},
  homunculus:{tag:'VERNUNFT UND MENSCHENBILD',title:'Ist der Mensch vernünftig – oder vor allem ein strebendes Wesen?',intro:'Formuliere die gegensätzlichen Menschenbilder aus dem „Prolog im Himmel“ als kurzen Dialog. Nutze eigene Worte und prüfe sie danach am Text.',transfer:'Der Herr und Mephistopheles beurteilen Faust verschieden. Untersuche, welche Annahmen über Irrtum, Vernunft und Entwicklung hinter der Wette stehen.'},
  fortschritt:{tag:'FREIHEIT UND VERANTWORTUNG',title:'Wie frei handelt Faust?',intro:'Schätze Fausts Handlungsspielraum und Mephistopheles’ Einfluss ein. Eine Zahl genügt nicht: Belege dein Urteil an einer konkreten Szene.',transfer:'Prüfe am Pakt und an der Gretchentragödie, wo Faust entscheidet, wo er beeinflusst wird und wofür er dennoch Verantwortung trägt.'}
};

export default function LifeLab({ moduleId }: { moduleId: string }) {
  const copy=labCopy[moduleId]; const [state,setState]=useState<LabState>({}); const [hydrated,setHydrated]=useState(false); const [seconds,setSeconds]=useState(60); const [running,setRunning]=useState(false);
  useEffect(()=>{ /* eslint-disable react-hooks/set-state-in-effect -- browser-only local workspace */ try{setState(JSON.parse(localStorage.getItem(`faust-lab-${moduleId}`)||'{}'));}catch{} setHydrated(true); /* eslint-enable react-hooks/set-state-in-effect */ },[moduleId]);
  useEffect(()=>{if(hydrated)localStorage.setItem(`faust-lab-${moduleId}`,JSON.stringify(state));},[hydrated,moduleId,state]);
  useEffect(()=>{if(!running||seconds<=0)return;const timer=window.setInterval(()=>setSeconds(value=>value-1),1000);return()=>window.clearInterval(timer);},[running,seconds]);
  if(!copy)return null;
  const set=(key:string,value:string|number|string[])=>setState(current=>({...current,[key]:value}));
  const field=(key:string,placeholder:string)=><textarea value={String(state[key]||'')} onChange={event=>set(key,event.target.value)} placeholder={placeholder}/>;
  const order=(state.order as string[])||['Wort','Sinn','Kraft','Tat'];
  const move=(index:number,direction:-1|1)=>{const next=[...order],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];set('order',next)};
  const messages=(state.messages as string[])||[];
  return <section className="lifeLab">
    <header><div><span>{copy.tag}</span><h2>{copy.title}</h2></div><p>{copy.intro}</p></header>
    <div className="labScreen">
      {moduleId==='werkstatt'&&<div className="overloadLab"><div className="signal"><strong>{state.certainty||50}%</strong><input aria-label="Grad der Gewissheit" type="range" min="0" max="100" value={Number(state.certainty||50)} onChange={e=>set('certainty',Number(e.target.value))}/><span>unsicher ← Grad der Gewissheit → sicher</span></div><label><span>Deine Frage</span>{field('question','Zum Beispiel: Woran erkenne ich, ob eine Information verlässlich ist?')}</label><label><span>Was weisst du – und wo beginnt deine Vermutung?</span>{field('boundary','Gesichert ist … / Ich vermute … / Offen bleibt …')}</label></div>}
      {moduleId==='krise'&&<div className="versionLab"><label><span>Wissen aus Texten</span>{field('books','Was lässt sich nachlesen oder belegen?')}</label><label><span>Eigene Erfahrung</span>{field('experience','Was zeigt dir eigenes Erproben?')}</label><label><span>Kriterium</span>{field('criterion','Wann hältst du eine Aussage für verlässlich?')}</label></div>}
      {moduleId==='natur'&&<div className="observationLab"><div className="timer"><strong>{seconds}</strong><span>Sekunden</span><button onClick={()=>{if(seconds===0)setSeconds(60);setRunning(value=>!value)}}>{seconds===0?'Neu starten':running?'Pause':'Beobachtung starten'}</button></div><div className="observationInputs">{[0,1,2,3,4].map(index=><label key={index}><span>Beobachtung {index+1}</span><input value={String(state[`obs${index}`]||'')} onChange={e=>set(`obs${index}`,e.target.value)} placeholder={index===0?'Nur sichtbar, hörbar oder fühlbar …':'Noch ein genaues Detail …'}/></label>)}</div></div>}
      {moduleId==='philosophie'&&<div className="remixLab"><div className="wordStack">{order.map((word,index)=><div key={word}><b>{index+1}</b><strong>{word}</strong><span><button disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button disabled={index===order.length-1} onClick={()=>move(index,1)}>↓</button></span></div>)}</div><label><span>Deine Begründung</span>{field('decision','Für meine Entscheidung … steht … zuerst, weil …')}</label></div>}
      {moduleId==='homunculus'&&<div className="chatLab"><div className="chatMessages">{messages.length?messages.map((message,index)=><p className={message.startsWith('HERR:')?'system':''} key={`${message}-${index}`}><span>{message.startsWith('HERR:')?'Der Herr':'Mephistopheles'}</span>{message.replace(/^(HERR:|MEPHISTO:)\s*/,'')}</p>):<div className="emptyChat">Noch keine Aussagen. Formuliert zuerst je eine Behauptung über den Menschen.</div>}</div><div className="chatComposer"><div><button className={state.speaker==='lord'?'active':''} onClick={()=>set('speaker','lord')}>Der Herr</button><button className={state.speaker!=='lord'?'active':''} onClick={()=>set('speaker','mephisto')}>Mephistopheles</button></div><input value={String(state.draft||'')} onChange={e=>set('draft',e.target.value)} placeholder="Der Mensch irrt, weil … / Der Mensch kann …"/><button onClick={()=>{const draft=String(state.draft||'').trim();if(!draft)return;set('messages',[...messages,`${state.speaker==='lord'?'HERR':'MEPHISTO'}: ${draft}`]);set('draft','')}}>Eintragen</button></div></div>}
      {moduleId==='fortschritt'&&<div className="impactLab"><label><span>Welche Szene untersuchst du?</span><input value={String(state.scene||'')} onChange={e=>set('scene',e.target.value)} placeholder="Zum Beispiel: Pakt, Strasse, Dom oder Kerker"/></label><div className="impactSliders"><label><span>Fausts Handlungsspielraum <b>{state.freedom||50}</b></span><input type="range" min="0" max="100" value={Number(state.freedom||50)} onChange={e=>set('freedom',Number(e.target.value))}/></label><label><span>Einfluss Mephistopheles’ <b>{state.influence||50}</b></span><input type="range" min="0" max="100" value={Number(state.influence||50)} onChange={e=>set('influence',Number(e.target.value))}/></label></div><div className="stakeholders"><label><span>Beleg für eigene Entscheidung</span>{field('choice','Faust entscheidet selbst, als …')}</label><label><span>Beleg für Beeinflussung</span>{field('pressure','Mephistopheles beeinflusst ihn, indem …')}</label></div></div>}
    </div>
    <footer><div><span>AM TEXT PRÜFEN</span><p>{copy.transfer}</p></div><label><span>Zu zweit: Welche andere Deutung ist möglich?</span><input value={String(state.partner||'')} onChange={e=>set('partner',e.target.value)} placeholder="Die andere Person deutet die Stelle anders, weil …"/></label></footer>
  </section>;
}
