'use client';

import { useEffect, useState } from 'react';
import MediaEvidence from './MediaEvidence';

type LabState = Record<string, string | number | string[]>;
const labCopy: Record<string, { tag:string; title:string; intro:string; transfer:string }> = {
  werkstatt:{tag:'ERKENNTNISGRENZEN',title:'Was weisst du – und was vermutest du nur?',intro:'Nimm eine Frage, bei der du gern Gewissheit hättest. Trenne gesichertes Wissen, begründete Vermutung und das, was vorerst offenbleibt.',transfer:'Faust behauptet, trotz seiner Studien nichts sicher zu wissen. Prüfe in „Nacht“, ob er eine methodische Grenze beschreibt oder aus Enttäuschung übertreibt.'},
  krise:{tag:'METHODE UND ERFAHRUNG',title:'Wie entsteht verlässliches Wissen?',intro:'Bücher, Messungen und eigene Erfahrungen liefern unterschiedliche Arten von Einsicht. Halte fest, was jede davon leisten kann – und was nicht.',transfer:'Vergleiche deine Kriterien mit Fausts und Wagners gegensätzlichem Verhältnis zu Studium, Überlieferung und Erfahrung.'},
  natur:{tag:'BEOBACHTUNG UND DEUTUNG',title:'Siehst du – oder deutest du schon?',intro:'Lege das Smartphone für 60 Sekunden mit dem Display nach unten. Beobachte einen Gegenstand und halte nur fest, was wirklich wahrnehmbar ist.',transfer:'Prüfe anschliessend: An welcher Stelle wurde aus einer Beobachtung eine Erklärung? Genau diese Grenze ist für wissenschaftliches Arbeiten entscheidend.'},
  philosophie:{tag:'SPRACHE UND SINN',title:'Welche Übersetzung überzeugt dich?',intro:'Faust prüft nacheinander Wort, Sinn, Kraft und Tat. Ordne die vier Begriffe und begründe deine Wahl an einer konkreten Entscheidung.',transfer:'Vergleiche deine Reihenfolge mit Fausts Übersetzung des Johannes-Prologs. Was gewinnt seine Entscheidung für die „Tat“ – und was verliert sie?'},
  homunculus:{tag:'VERNUNFT UND MENSCHENBILD',title:'Ist der Mensch vernünftig – oder vor allem ein strebendes Wesen?',intro:'Formuliere die gegensätzlichen Menschenbilder aus dem „Prolog im Himmel“ als kurzen Dialog. Nutze eigene Worte und prüfe sie danach am Text.',transfer:'Der Herr und Mephistopheles beurteilen Faust verschieden. Untersuche, welche Annahmen über Irrtum, Vernunft und Entwicklung hinter der Wette stehen.'},
  fortschritt:{tag:'FREIHEIT UND VERANTWORTUNG',title:'Wie frei handelt Faust?',intro:'Schätze Fausts Handlungsspielraum und Mephistopheles’ Einfluss ein. Eine Zahl genügt nicht: Belege dein Urteil an einer konkreten Szene.',transfer:'Prüfe am Pakt und an der Gretchentragödie, wo Faust entscheidet, wo er beeinflusst wird und wofür er dennoch Verantwortung trägt.'}
};
type Experiment={title:string;time:string;materials:string[];steps:string[];sense:string;question:string;quote:string;scene:string;textTrail?:{quote:string;label:string;prompt:string}[]};
const experiments:Record<string,Experiment>={
 werkstatt:{title:'Faust im Tastlabor: Wann wird aus wenig Wissen ein Totalurteil?',time:'15 Min.',materials:['undurchsichtiger Stoffbeutel oder Etui','zwei unbekannte kleine Gegenstände','vier Zettel: BEFUND · SCHLUSS · SICHERHEIT · OFFEN'],steps:['Person A versteckt zwei Gegenstände. Person B tastet nur einen davon für 20 Sekunden. Kein Raten: B nennt zunächst drei einzelne Befunde – etwa „kantig“, „kalt“ oder „beweglich“.','B sagt nun, was der Gegenstand vermutlich ist. Person C legt zu jedem Satz den passenden Zettel: BEFUND, SCHLUSS, SICHERHEIT oder OFFEN. Wo vermischen sich die Ebenen?','B tastet den zweiten Gegenstand mit einer Zusatzmethode: schütteln, wiegen oder daran riechen. Entscheidet vor dem Öffnen: Welche Methode hat welche Unsicherheit verringert?','Öffnet den Beutel. Korrigiert nicht bloss den Namen des Gegenstands: Markiert genau, welcher Befund trug, welcher Schluss zu weit ging und was weiterhin unbekannt bleibt.'],sense:'Notiere wortwörtlich: drei Tastbefunde, deinen ersten Schluss und den Satz, mit dem du deine Sicherheit ausgedrückt hast.',question:'Faust hat tatsächlich viel studiert. Darf er aus der Enttäuschung über die Reichweite dieses Wissens folgern, dass „wir nichts wissen können“ – oder verwechselt er begrenztes Wissen mit Nichtwissen?',quote:'„Habe nun, ach! Philosophie … durchaus studiert … / Da steh ich nun, ich armer Tor! / Und sehe, dass wir nichts wissen können!“',scene:'Nacht · vom überprüfbaren Studieninventar zum Totalurteil',textTrail:[{quote:'„Habe nun, ach! Philosophie, / Juristerei und Medizin … durchaus studiert“',label:'1 · Bestand',prompt:'Wie beim Ertasten: Das ist eine überprüfbare Angabe darüber, was Faust getan hat.'},{quote:'„Da steh ich nun, ich armer Tor!“',label:'2 · Selbsturteil',prompt:'Aus dem Bestand wird eine Abwertung der eigenen Person. Welche Messlatte benutzt Faust?'},{quote:'„Und bin so klug als wie zuvor“',label:'3 · Bilanz',prompt:'Faust vergleicht sein heutiges Wissen mit früher. Liefert der Text dafür einen überprüfbaren Massstab?'},{quote:'„Dass wir nichts wissen können!“',label:'4 · Sprung ins Allgemeine',prompt:'Aus „ich bin enttäuscht“ wird eine Aussage über alle Menschen und alles Wissen. Genau dieser Sprung steht zur Prüfung.'}]},
 krise:{title:'Das Pendel: Buchregel gegen Handerfahrung',time:'12 Min.',materials:['Faden','Radiergummi oder Schlüssel','Lineal','Stoppuhr'],steps:['Bindet den Gegenstand an 20 cm Faden. Sagt voraus, wie lange zehn Schwingungen dauern, und messt danach.','Wiederholt mit 40 cm Faden. Verändert nur die Länge; lasst Auslenkung und Gewicht möglichst gleich.','Vergleicht Vorwissen, Messwert und mögliche Fehler. Formuliert eine Regel, die ein anderes Tandem prüfen könnte.'],sense:'Was konntet ihr sehen, hören oder im Faden spüren? Welche Zahl stammt erst aus eurer Messordnung?',question:'Braucht Erkenntnis Wagners geduldige Methode, Fausts unmittelbare Erfahrung – oder gerade deren kontrollierte Verbindung?',quote:'„Zwar weiß ich viel, doch möcht’ ich alles wissen.“',scene:'Nacht · Wagner'},
 natur:{title:'Ein Papierkörper, zwei Schattenwelten',time:'10 Min.',materials:['ein zerknülltes Blatt Papier','weisses Blatt','Handy-Taschenlampe','Stift'],steps:['Legt den Papierkörper auf das Blatt und beleuchtet ihn flach von links. Zeichnet nur den Umriss des Schattens.','Beleuchtet denselben Körper von oben oder rechts und zeichnet den neuen Umriss daneben.','Vergleicht: gleicher Gegenstand, andere Erscheinung. Benennt, was Lichtposition und Perspektive jeweils unsichtbar machen.'],sense:'Notiere nur sichtbare Veränderungen von Kontur, Länge, Helligkeit und Oberfläche – noch keine Erklärung.',question:'Ist einer der Schatten „der wahre“ Gegenstand? Was leistet ein begrenztes Bild, obwohl es nie das Ganze zeigt?',quote:'„Welch Schauspiel! aber ach! ein Schauspiel nur!“',scene:'Nacht · Zeichen des Makrokosmos'},
 philosophie:{title:'Vier Wortkarten werden zu vier Handlungen',time:'10 Min.',materials:['vier Papierkarten','dicker Stift','etwas freie Tisch- oder Bodenfläche'],steps:['Schreibt WORT, SINN, KRAFT und TAT je auf eine Karte und legt sie in eine Reihenfolge.','Eine Person spricht „Im Anfang war …“ mit jeder Karte; eine zweite erfindet spontan eine passende Geste.','Verschiebt die Karten. Beobachtet, wie Körperhaltung, Betonung und Erwartung sich ändern, obwohl nur ein Wort wechselt.'],sense:'Welche Karte führte zu welcher Geste, Betonung oder körperlichen Spannung?',question:'Entdeckt Faust die richtige Übersetzung – oder erzeugt jede Wortwahl eine andere Wirklichkeit des Anfangs?',quote:'„Im Anfang war die Tat!“',scene:'Studierzimmer I · Übersetzung'},
 homunculus:{title:'Streben unter sichtbarem Risiko',time:'10 Min.',materials:['Papierball','Papierkorb oder Schachtel','Klebeband als drei Abwurflinien'],steps:['Markiert drei Distanzen. Jede Person wählt vor dem ersten Wurf: nah = 1 Punkt, mittel = 2, weit = 4.','Wer trifft, darf aufhören oder weiter von hinten werfen; ein Fehlwurf löscht nur die Punkte dieser Runde. Spielt drei Runden.','Legt die Entscheidungen offen: Wann habt ihr trotz besserer Einsicht riskiert? War der Irrtum lernfördernd oder bloss vermeidbar?'],sense:'Beschreibe den Moment vor einem riskanten Wurf: Körperanspannung, Impuls, Erwartung und tatsächliches Ergebnis.',question:'Bestätigt euer Verhalten den Herrn, weil Irrtum zum Streben gehört, oder Mephistopheles, weil Vernunft zur Rechtfertigung des Impulses dient?',quote:'„Es irrt der Mensch, solang er strebt.“',scene:'Prolog im Himmel · Der Herr'},
 fortschritt:{title:'Die gelenkte Wahl',time:'10 Min.',materials:['drei möglichst ähnliche Stifte oder Karten','ein auffälliges Blatt als Unterlage','Papier für Strichliste'],steps:['Person A legt drei Gegenstände neutral aus. Person B wählt schnell einen; notiert die Wahl.','Ohne Kommentar wird nun ein Gegenstand auf die auffällige Unterlage gelegt und näher zur wählenden Person geschoben. Wählt erneut.','Tauscht Rollen. Klärt erst danach die Absicht: War die zweite Wahl frei, beeinflusst oder manipuliert – und wer trägt wofür Verantwortung?'],sense:'Welche Farbe, Lage, Nähe oder Bewegung hat deine Aufmerksamkeit zuerst körperlich angezogen?',question:'Ein Einfluss verursacht noch keine Entscheidung. Welche Information, Alternative oder Täuschung verändert dennoch den Grad der Verantwortung?',quote:'„Werd’ ich zum Augenblicke sagen: / Verweile doch! du bist so schön!“',scene:'Studierzimmer II · Pakt und Wette'}
};

export default function LifeLab({ moduleId }: { moduleId: string }) {
  const copy=labCopy[moduleId]; const experiment=experiments[moduleId]; const [state,setState]=useState<LabState>({}); const [hydrated,setHydrated]=useState(false); const [seconds,setSeconds]=useState(60); const [running,setRunning]=useState(false);
  useEffect(()=>{ /* eslint-disable react-hooks/set-state-in-effect -- browser-only local workspace */ try{setState(JSON.parse(localStorage.getItem(`faust-lab-${moduleId}`)||'{}'));}catch{} setHydrated(true); /* eslint-enable react-hooks/set-state-in-effect */ },[moduleId]);
  useEffect(()=>{if(hydrated)localStorage.setItem(`faust-lab-${moduleId}`,JSON.stringify(state));},[hydrated,moduleId,state]);
  useEffect(()=>{if(!running||seconds<=0)return;const timer=window.setInterval(()=>setSeconds(value=>value-1),1000);return()=>window.clearInterval(timer);},[running,seconds]);
  if(!copy)return null;
  const set=(key:string,value:string|number|string[])=>setState(current=>({...current,[key]:value}));
  const field=(key:string,placeholder:string)=><textarea value={String(state[key]||'')} onChange={event=>set(key,event.target.value)} placeholder={placeholder}/>;
  const order=(state.order as string[])||['Wort','Sinn','Kraft','Tat'];
  const move=(index:number,direction:-1|1)=>{const next=[...order],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];set('order',next)};
  const messages=(state.messages as string[])||[];
  return <section className="lifeLab">
    <header><div><span>{copy.tag}</span><h2>{copy.title}</h2></div><p>{copy.intro}</p></header>
    <section className={`sensoryExperiment ${moduleId==='werkstatt'?'faustBox':''}`}><header><div><span>ANFASSEN · BEOBACHTEN · FAUSTS SCHLUSS PRÜFEN</span><h3>{experiment.title}</h3></div><b>{experiment.time}</b></header><div className="experimentKit"><span>Ihr braucht</span>{experiment.materials.map(item=><b key={item}>{item}</b>)}</div><ol>{experiment.steps.map((step,index)=><li className={Number(state.expStep||0)>index?'done':''} key={step}><button onClick={()=>set('expStep',Math.max(Number(state.expStep||0),index+1))}><span>{Number(state.expStep||0)>index?'✓':index+1}</span><p>{step}</p></button></li>)}</ol>{experiment.textTrail&&<div className="textTrail"><header><span>Derselbe Denkweg in „Nacht“</span><h4>Tippe die vier Stationen an: Wo verlässt Faust den sicheren Befund?</h4></header><div>{experiment.textTrail.map((item,index)=>{const open=Number(state.textTrail||0)>index;return <button className={open?'open':''} key={item.quote} onClick={()=>set('textTrail',Math.max(Number(state.textTrail||0),index+1))}><span>{item.label}</span><blockquote>{item.quote}</blockquote><p>{open?item.prompt:'Gedankenschritt aufdecken'}</p></button>})}</div></div>}<MediaEvidence moduleId={moduleId} note={String(state.mediaNote||'')} onNote={value=>set('mediaNote',value)}/><div className="senseBridge"><label><span>{moduleId==='werkstatt'?'Versuchsprotokoll in Originalworten':'Sinnesprotokoll – noch keine Deutung'}</span>{field('sensoryObservation',experiment.sense)}</label><article><span>Rückbindung an Faust I</span><blockquote>{experiment.quote}</blockquote><small>{experiment.scene}</small><p>{experiment.question}</p></article><label><span>{moduleId==='werkstatt'?'Dein Urteil über Fausts Schluss':'Denkantwort mit Textbezug'}</span>{field('sensoryThought',moduleId==='werkstatt'?'Faust weiss nachweislich … Unbefriedigend ist für ihn … Zu weit geht sein Schluss dort, wo … Berechtigt wäre stattdessen …':'Im Experiment habe ich … wahrgenommen. Daraus schloss ich … Die Textstelle zeigt ähnlich / anders … Deshalb …')}</label></div></section>
    <div className="labScreen">
      {moduleId==='werkstatt'&&<div className="overloadLab"><div className="signal"><strong>{state.certainty||50}%</strong><input aria-label="Grad der Gewissheit" type="range" min="0" max="100" value={Number(state.certainty||50)} onChange={e=>set('certainty',Number(e.target.value))}/><span>unsicher ← Grad der Gewissheit → sicher</span></div><label><span>Deine Frage</span>{field('question','Zum Beispiel: Woran erkenne ich, ob eine Information verlässlich ist?')}</label><label><span>Was weisst du – und wo beginnt deine Vermutung?</span>{field('boundary','Gesichert ist … / Ich vermute … / Offen bleibt …')}</label></div>}
      {moduleId==='krise'&&<div className="versionLab"><label><span>Wissen aus Texten</span>{field('books','Was lässt sich nachlesen oder belegen?')}</label><label><span>Eigene Erfahrung</span>{field('experience','Was zeigt dir eigenes Erproben?')}</label><label><span>Kriterium</span>{field('criterion','Wann hältst du eine Aussage für verlässlich?')}</label></div>}
      {moduleId==='natur'&&<div className="observationLab"><div className="timer"><strong>{seconds}</strong><span>Sekunden</span><button onClick={()=>{if(seconds===0)setSeconds(60);setRunning(value=>!value)}}>{seconds===0?'Neu starten':running?'Pause':'Beobachtung starten'}</button></div><div className="observationInputs">{[0,1,2,3,4].map(index=><label key={index}><span>Beobachtung {index+1}</span><input value={String(state[`obs${index}`]||'')} onChange={e=>set(`obs${index}`,e.target.value)} placeholder={index===0?'Nur sichtbar, hörbar oder fühlbar …':'Noch ein genaues Detail …'}/></label>)}</div></div>}
      {moduleId==='philosophie'&&<div className="remixLab"><div className="wordStack">{order.map((word,index)=><div key={word}><b>{index+1}</b><strong>{word}</strong><span><button disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button disabled={index===order.length-1} onClick={()=>move(index,1)}>↓</button></span></div>)}</div><label><span>Deine Begründung</span>{field('decision','Für meine Entscheidung … steht … zuerst, weil …')}</label></div>}
      {moduleId==='homunculus'&&<div className="chatLab"><div className="chatMessages">{messages.length?messages.map((message,index)=><p className={message.startsWith('HERR:')?'system':''} key={`${message}-${index}`}><span>{message.startsWith('HERR:')?'Der Herr':'Mephistopheles'}</span>{message.replace(/^(HERR:|MEPHISTO:)\s*/,'')}</p>):<div className="emptyChat">Noch keine Aussagen. Formuliert zuerst je eine Behauptung über den Menschen.</div>}</div><div className="chatComposer"><div><button className={state.speaker==='lord'?'active':''} onClick={()=>set('speaker','lord')}>Der Herr</button><button className={state.speaker!=='lord'?'active':''} onClick={()=>set('speaker','mephisto')}>Mephistopheles</button></div><input value={String(state.draft||'')} onChange={e=>set('draft',e.target.value)} placeholder="Der Mensch irrt, weil … / Der Mensch kann …"/><button onClick={()=>{const draft=String(state.draft||'').trim();if(!draft)return;set('messages',[...messages,`${state.speaker==='lord'?'HERR':'MEPHISTO'}: ${draft}`]);set('draft','')}}>Eintragen</button></div></div>}
      {moduleId==='fortschritt'&&<div className="impactLab"><label><span>Welche Szene untersuchst du?</span><input value={String(state.scene||'')} onChange={e=>set('scene',e.target.value)} placeholder="Zum Beispiel: Pakt, Strasse, Dom oder Kerker"/></label><div className="impactSliders"><label><span>Fausts Handlungsspielraum <b>{state.freedom||50}</b></span><input type="range" min="0" max="100" value={Number(state.freedom||50)} onChange={e=>set('freedom',Number(e.target.value))}/></label><label><span>Einfluss Mephistopheles’ <b>{state.influence||50}</b></span><input type="range" min="0" max="100" value={Number(state.influence||50)} onChange={e=>set('influence',Number(e.target.value))}/></label></div><div className="stakeholders"><label><span>Beleg für eigene Entscheidung</span>{field('choice','Faust entscheidet selbst, als …')}</label><label><span>Beleg für Beeinflussung</span>{field('pressure','Mephistopheles beeinflusst ihn, indem …')}</label></div></div>}
    </div>
    <footer><div><span>AM TEXT PRÜFEN</span><p>{copy.transfer}</p></div><label><span>Zu zweit: Welche andere Deutung ist möglich?</span><input value={String(state.partner||'')} onChange={e=>set('partner',e.target.value)} placeholder="Die andere Person deutet die Stelle anders, weil …"/></label></footer>
  </section>;
}
