'use client';

import { useEffect, useState } from 'react';
import { TextFeedback } from '../feedback';

const disciplines=[
 {name:'Philosophie',scene:'Nacht · Studierzimmer I',question:'Kann Denken die Welt als Ganzes erfassen?',faust:'Faust will verstehen, „was die Welt im Innersten zusammenhält“. Er misst das Fach am Anspruch umfassender Erkenntnis.',mephisto:'Mephistopheles karikiert Logik und Metaphysik als starre Lehrgänge. Er trifft leere Routinen, ersetzt Argumente aber durch Spott.'},
 {name:'Rechtswissenschaft',scene:'Nacht · Studierzimmer II',question:'Schützt Recht das Gerechte – oder nur das Überlieferte?',faust:'Faust zählt das Fach zu einer Ausbildung, die seine Erkenntniskrise nicht lösen konnte. Sein Urteil bleibt zunächst pauschal.',mephisto:'Mephistopheles verspottet überlieferte Gesetze. Er benennt Veränderungsbedarf, bietet aber keine gerechtere Ordnung an.'},
 {name:'Medizin',scene:'Nacht · Vor dem Tor · Studierzimmer II',question:'Was schuldet Wissen den Menschen, die ihm vertrauen?',faust:'Faust zweifelt rückblickend am Nutzen früherer Heilversuche. Medizin wird zur Frage nach Evidenz und Verantwortung.',mephisto:'Mephistopheles reduziert medizinisches Können auf oberflächliche Erfahrung und persönliche Wirkung. Prüfung und Würde geraten aus dem Blick.'},
 {name:'Theologie',scene:'Nacht · Prolog im Himmel · Studierzimmer I',question:'Wie lassen sich Glaube, Zweifel und Wissen zueinander bestimmen?',faust:'Faust findet im Studium keine Gewissheit, übersetzt den Johannes-Prolog aber selbst und ringt produktiv mit seiner Bedeutung.',mephisto:'Mephistopheles stört Sinn- und Heilsgewissheiten. Seine Verneinung ist jedoch interessengeleitet und keine neutrale Kritik.'}
];

const schools=[
 {key:'uzh',name:'Universität Zürich',type:'Universitäres Fächerspektrum',note:'Prüfe bei jedem Fach, wie stark Theorie, Forschung, Methodenbildung und mögliche Praxisfelder tatsächlich gewichtet werden.',examples:'Suche drei Bachelorprogramme, die dieselbe Grundfrage mit verschiedenen Methoden bearbeiten.',url:'https://www.uzh.ch/de/studies/programs.html'},
 {key:'zhaw',name:'ZHAW',type:'Angewandte Wissenschaften',note:'Die Übersicht nennt 34 Bachelorstudiengänge und betont wissenschaftlich fundierte berufliche Qualifikation. Prüfe trotzdem den Grundlagenanteil jedes Programms.',examples:'Vergleiche etwa ein technisches, ein gesundheitliches und ein sprachlich-soziales Programm.',url:'https://www.zhaw.ch/de/studium/bachelorstudiengaenge'},
 {key:'unilu',name:'Universität Luzern',type:'Universitäres Studienangebot',note:'Das Angebot führt unter anderem Theologie, Kultur- und Sozialwissenschaften, Recht, Wirtschaft, Gesundheit/Medizin und Psychologie zusammen.',examples:'Suche Programme, in denen Menschenbild, Normen oder gesellschaftliche Verantwortung zentral sind.',url:'https://www.unilu.ch/studium/studienangebot/'}
] as const;

type SchoolKey=typeof schools[number]['key'];
type LabState={step:number;discipline:number;foundation:number;explain:number;method:number;crisis:string;mephReply:string;knowledge:string;spectrumReason:string;disciplineNote:string;schoolNotes:Record<SchoolKey,string>;candidate1:string;candidate2:string;candidate3:string;comparison:string;objection:string;nextStep:string};
const initial:LabState={step:0,discipline:0,foundation:50,explain:50,method:50,crisis:'',mephReply:'',knowledge:'',spectrumReason:'',disciplineNote:'',schoolNotes:{uzh:'',zhaw:'',unilu:''},candidate1:'',candidate2:'',candidate3:'',comparison:'',objection:'',nextStep:''};
const steps=['Gelehrtenkrise','Erkenntnisprofil','Fächerstreit','Hochschulrecherche','Begründete Shortlist'];

export default function Studienwahllabor(){
 const [state,setState]=useState<LabState>(initial);const [ready,setReady]=useState(false);
 useEffect(()=>{/* eslint-disable react-hooks/set-state-in-effect -- browser-only local workspace */try{const saved=JSON.parse(localStorage.getItem('faust-studienwahl-parcours')||'{}');setState({...initial,...saved,schoolNotes:{...initial.schoolNotes,...saved.schoolNotes}});}catch{}setReady(true);/* eslint-enable react-hooks/set-state-in-effect */},[]);
 useEffect(()=>{if(ready)localStorage.setItem('faust-studienwahl-parcours',JSON.stringify(state));},[ready,state]);
 const set=<K extends keyof LabState>(key:K,value:LabState[K])=>setState(current=>({...current,[key]:value}));
 const field=(key:keyof LabState,placeholder:string,rows=4)=><textarea rows={rows} value={String(state[key])} onChange={e=>set(key,e.target.value as never)} placeholder={placeholder}/>;
 const d=disciplines[state.discipline];
 const finish=`${state.candidate1} ${state.candidate2} ${state.candidate3} ${state.comparison} ${state.objection} ${state.nextStep}`;
 return <section className="studyChoiceLab studyParcours" id="studienwahl">
  <header><div><p className="worldEyebrow">Studienwahl-Parcours · Faust I</p><h2>Was willst du<br/>wirklich wissen?</h2></div><p>Faust kennt viele Fächer und findet trotzdem keine Richtung. Dieser Parcours macht seine Gelehrtenkrise zum Prüfstein: Suchst du Erkenntnis um ihrer selbst willen, eine konkrete Wirkung – oder eine begründete Verbindung von beidem?</p></header>
  <nav className="parcoursNav" aria-label="Schritte des Studienwahl-Parcours">{steps.map((label,index)=><button key={label} className={state.step===index?'active':state.step>index?'visited':''} onClick={()=>set('step',index)}><span>{state.step>index?'✓':index+1}</span><strong>{label}</strong></button>)}</nav>
  <div className="parcoursStage">
   {state.step===0&&<div className="crisisStage"><div className="stageLead"><span>01 · Ausgangspunkt</span><h3>Faust hat Abschlüsse.<br/>Aber keine Orientierung.</h3><p>In „Nacht“ zählt Faust Philosophie, Recht, Medizin und Theologie auf. Sein Problem ist nicht Informationsmangel: Er zweifelt an Reichweite, Wirkung und Sinn seines Wissens.</p></div><div className="parcoursFields"><label><span>Diagnose der Gelehrtenkrise</span>{field('crisis','Faust fehlt nicht Wissen über …, sondern …; er erwartet von Wissenschaft …')}</label><label><span>Mephistopheles widerspricht</span>{field('mephReply','Mephistopheles könnte einwenden: Du suchst im Studium …, obwohl …')}</label><label><span>Übertragung auf deine Studienwahl</span>{field('knowledge','Von einem Studium erwarte ich Erkenntnis über … und Wirkung auf …; es kann mir aber nicht abnehmen …')}</label><TextFeedback prompt="Erkläre Fausts Gelehrtenkrise als Erkenntnis-, Wirkungs- und Sinnproblem. Übertrage sie begründet auf deine Studienwahl und formuliere eine Grenze dessen, was ein Studium leisten kann." answer={`${state.crisis} ${state.mephReply} ${state.knowledge}`}/></div></div>}
   {state.step===1&&<div className="profileStage"><div className="stageLead"><span>02 · Wissenschaftstheorie</span><h3>Grundlagen verstehen oder Probleme lösen?</h3><p>Das ist kein Entweder-oder. Platziere dich auf drei Spektren und begründe, welche Verbindung du suchst.</p></div><div className="spectrumBoard">{([['foundation','Grundlagenwissenschaft','Angewandte Disziplin'],['explain','Erklären und verstehen','Entwerfen und verändern'],['method','Text, Begriff, Argument','Beobachtung, Daten, Experiment']] as const).map(([key,left,right])=><label key={key}><div><strong>{left}</strong><b>{state[key]}</b><strong>{right}</strong></div><input type="range" min="0" max="100" value={state[key]} onChange={e=>set(key,Number(e.target.value))}/></label>)}<div className="spectrumQuestions"><article><span>Faustische Frage</span><p>Welche Wahrheit wäre dir wichtig, selbst wenn sie noch keinen unmittelbaren Nutzen hat?</p></article><article><span>Mephistophelische Prüfung</span><p>Woran würdest du erkennen, dass deine grossen Begriffe in der Wirklichkeit etwas erklären oder verbessern?</p></article></div><label className="wideField"><span>Deine Verbindung von Erkenntnis und Anwendung</span>{field('spectrumReason','Ich möchte zuerst … verstehen, um später …; eine Anwendung ohne Grundlagen wäre problematisch, weil …',5)}</label></div></div>}
   {state.step===2&&<div className="disciplineStage"><div className="stageLead"><span>03 · Fächerstreit</span><h3>Vier Disziplinen aus zwei Perspektiven</h3><p>Die Fächer sind keine Persönlichkeitstypen. Prüfe ihre Erkenntnisfragen und Methoden.</p></div><div className="disciplineTabs">{disciplines.map((item,index)=><button key={item.name} className={state.discipline===index?'active':''} onClick={()=>set('discipline',index)}>{item.name}</button>)}</div><div className="disciplineQuestion"><span>Leitfrage</span><h4>{d.question}</h4><small>{d.scene}</small></div><div className="perspectiveDesk"><article className="faustView"><div className="perspectiveHead"><span>F</span><div><small>Faustische Perspektive</small><h3>Erkenntnis suchen</h3></div></div><p>{d.faust}</p></article><div className="versus">↔</div><article className="mephistoView"><div className="perspectiveHead"><span>M</span><div><small>Mephistophelische Perspektive</small><h3>Ansprüche prüfen</h3></div></div><p>{d.mephisto}</p></article></div><label className="parcoursSingle"><span>Dein Urteil zum Fach</span>{field('disciplineNote',`An ${d.name} interessiert mich die Frage …; Fausts Anspruch überzeugt mich, weil …; Mephistopheles’ Einwand trifft zu, wenn …`,6)}</label></div>}
   {state.step===3&&<div className="researchStage"><div className="stageLead"><span>04 · Wirklichkeitstest</span><h3>Drei Hochschulen. Nicht nur drei Etiketten.</h3><p>Öffne die offiziellen Angebote. Suche nicht bloss nach einem wohlklingenden Titel: Prüfe Module, Methoden, Voraussetzungen und die tatsächliche Verbindung von Grundlagen und Anwendung.</p></div><div className="schoolGrid">{schools.map(school=><article key={school.key}><div><span>{school.type}</span><h4>{school.name}</h4></div><p>{school.note}</p><p className="researchPrompt">{school.examples}</p><a href={school.url} target="_blank" rel="noreferrer">Offizielles Studienangebot öffnen ↗</a><label><span>Rechercheprotokoll</span><textarea rows={6} value={state.schoolNotes[school.key]} onChange={e=>set('schoolNotes',{...state.schoolNotes,[school.key]:e.target.value})} placeholder="Programme: … / typische Module oder Methoden: … / Grundlagenanteil: … / Anwendungsbezug: … / offene Frage: …"/></label></article>)}</div><div className="sourceNote">Angebote und Zulassungsbedingungen können sich ändern. Entscheidend sind die verlinkten offiziellen Hochschulseiten; Stand der Prüfung: 03.09.2026.</div></div>}
   {state.step===4&&<div className="shortlistStage"><div className="stageLead"><span>05 · Vorläufiges Urteil</span><h3>Eine Shortlist, die Widerspruch aushält.</h3><p>Faust warnt vor Wissen ohne Orientierung. Mephistopheles warnt – oft zynisch – vor grossen Worten ohne Wirklichkeitsprüfung. Nutze beide Stimmen.</p></div><div className="candidateGrid">{(['candidate1','candidate2','candidate3'] as const).map((key,index)=><label key={key}><span>Kandidat {index+1}</span>{field(key,'Studiengang + Hochschule + wichtigste Erkenntnisfrage',4)}</label>)}</div><div className="finalReasoning"><label><span>Vergleich nach denselben Kriterien</span>{field('comparison','Kandidat 1 ist grundlagenorientierter, weil die Module …; Kandidat 2 verbindet … mit …; bei Kandidat 3 ist noch unklar …',6)}</label><label><span>Stärkster faustischer oder mephistophelischer Einwand</span>{field('objection','Der stärkste Einwand gegen meine erste Wahl lautet …; ich antworte darauf …',5)}</label><label><span>Nächster überprüfbarer Schritt</span>{field('nextStep','Bis zum … besuche ich … / lese ich das Modulhandbuch … / frage ich bei der Studienberatung …',4)}</label><TextFeedback prompt="Erstelle eine begründete Shortlist aus drei Studiengängen. Vergleiche sie anhand derselben wissenschaftstheoretischen Kriterien, prüfe Grundlagen und Anwendung, beantworte einen starken Einwand und formuliere einen konkreten nächsten Rechercheschritt." answer={finish}/></div></div>}
  </div>
  <footer className="parcoursControls"><button disabled={state.step===0} onClick={()=>set('step',state.step-1)}>← Zurück</button><div><span>Schritt {state.step+1} von {steps.length}</span><i><b style={{width:`${((state.step+1)/steps.length)*100}%`}}/></i></div><button disabled={state.step===steps.length-1} onClick={()=>set('step',state.step+1)}>Weiter →</button></footer>
 </section>;
}
