'use client';

import { useEffect, useState } from 'react';
import { TextFeedback } from '../feedback';

const disciplines=[
 {name:'Philosophie',scene:'Nacht · Studierzimmer I',question:'Kann Denken die Welt als Ganzes erfassen?',faust:'Faust will verstehen, „was die Welt im Innersten zusammenhält“. Er misst das Fach am Anspruch umfassender Erkenntnis.',mephisto:'Mephistopheles karikiert Logik und Metaphysik als starre Lehrgänge. Er trifft leere Routinen, ersetzt Argumente aber durch Spott.'},
 {name:'Rechtswissenschaft',scene:'Nacht · Studierzimmer II',question:'Schützt Recht das Gerechte – oder nur das Überlieferte?',faust:'Faust zählt das Fach zu einer Ausbildung, die seine Erkenntniskrise nicht lösen konnte. Sein Urteil bleibt zunächst pauschal.',mephisto:'Mephistopheles verspottet überlieferte Gesetze. Er benennt Veränderungsbedarf, bietet aber keine gerechtere Ordnung an.'},
 {name:'Medizin',scene:'Nacht · Vor dem Tor · Studierzimmer II',question:'Was schuldet Wissen den Menschen, die ihm vertrauen?',faust:'Faust zweifelt rückblickend am Nutzen früherer Heilversuche. Medizin wird zur Frage nach Evidenz und Verantwortung.',mephisto:'Mephistopheles reduziert medizinisches Können auf oberflächliche Erfahrung und persönliche Wirkung. Prüfung und Würde geraten aus dem Blick.'},
 {name:'Theologie',scene:'Nacht · Prolog im Himmel · Studierzimmer I',question:'Wie lassen sich Glaube, Zweifel und Wissen zueinander bestimmen?',faust:'Faust findet im Studium keine Gewissheit, übersetzt den Johannes-Prolog aber selbst und ringt produktiv mit seiner Bedeutung.',mephisto:'Mephistopheles stört Sinn- und Heilsgewissheiten. Seine Verneinung ist jedoch interessengeleitet und keine neutrale Kritik.'}
];

const schools=[
 {key:'uzh',name:'Universität Zürich',type:'Universitäres Fächerspektrum',note:'Prüfe bei jedem Fach, wie stark Theorie, Forschung, Methodenbildung und mögliche Praxisfelder tatsächlich gewichtet werden.',examples:'Suche drei Bachelorprogramme, die dieselbe Grundfrage mit verschiedenen Methoden bearbeiten.',url:'https://www.uzh.ch/de/studies/programs.html'},
 {key:'zhaw',name:'ZHAW',type:'Angewandte Wissenschaften',note:'Die Übersicht nennt 34 Bachelorstudiengänge und betont wissenschaftlich fundierte berufliche Qualifikation. Prüfe trotzdem den Grundlagenanteil jedes Programms.',examples:'Vergleiche etwa ein technisches, ein gesundheitliches und ein sprachlich-soziales Programm.',url:'https://www.zhaw.ch/de/studium/bachelorstudiengaenge'},
 {key:'unilu',name:'Universität Luzern',type:'Universitäres Studienangebot',note:'Das Angebot führt unter anderem Theologie, Kultur- und Sozialwissenschaften, Recht, Wirtschaft, Gesundheit/Medizin und Psychologie zusammen.',examples:'Suche Programme, in denen Menschenbild, Normen oder gesellschaftliche Verantwortung zentral sind.',url:'https://www.unilu.ch/studium/studienangebot/'}
] as const;

const disciplinePractice:Record<string,{work:string;sample:string;check:string[]}>= {
 Philosophie:{work:'Texte langsam lesen, Argumente rekonstruieren, Begriffe unterscheiden, Einwände schreiben und im Seminar diskutieren.',sample:'Konkrete Probe: Rekonstruiere in 150 Wörtern ein Argument zur Frage, ob nützliches Wissen auch wahres Wissen sein muss.',check:['Lese ich gern anspruchsvolle Texte mehrfach?','Kann ich eigene Überzeugungen gegen Einwände verteidigen?','Halte ich offene Fragen aus?']},
 Rechtswissenschaft:{work:'Fälle lesen, Normen auslegen, Tatbestände prüfen, unterschiedliche Rechtsgüter abwägen und Urteile begründen.',sample:'Konkrete Probe: Entscheide einen Konflikt zwischen zwei Rechten und lege offen, welche Regel du wie auslegst.',check:['Arbeite ich sprachlich genau?','Interessieren mich Regeln und ihre Begründung?','Kann ich mehrere vertretbare Positionen vergleichen?']},
 Medizin:{work:'Naturwissenschaftliche Grundlagen lernen, Evidenz beurteilen, diagnostische Entscheidungen üben und Verantwortung gegenüber Menschen übernehmen.',sample:'Konkrete Probe: Vergleiche zwei Therapieaussagen nach Studiendesign, Nutzen, Risiko und Unsicherheit.',check:['Interessieren mich biologische Zusammenhänge?','Kann ich unter Unsicherheit sorgfältig entscheiden?','Will ich Wissen mit Verantwortung für Menschen verbinden?']},
 Theologie:{work:'Biblische und historische Quellen auslegen, religiöse Traditionen vergleichen sowie ethische und systematische Fragen argumentativ bearbeiten.',sample:'Konkrete Probe: Lege eine Textstelle historisch und gegenwartsbezogen aus und benenne, wo beide Lesarten in Spannung geraten.',check:['Interessieren mich Sinn- und Wahrheitsfragen?','Arbeite ich gern mit Text, Geschichte und Argument?','Kann ich Glaubenspositionen kritisch und respektvoll prüfen?']}
};

const schoolExamples:Record<string,string[]>={
 uzh:['Philosophie','Religionswissenschaft und Theologie','Rechtswissenschaft','Humanmedizin'],
 zhaw:['Data Science','Angewandte Psychologie','Mehrsprachige Kommunikation','Gesundheitsförderung und Prävention'],
 unilu:['Philosophie','Philosophy, Politics and Economics','Rechtswissenschaft','Theologie']
};

type SchoolKey=typeof schools[number]['key'];
type LabState={step:number;discipline:number;foundation:number;explain:number;method:number;crisis:string;mephReply:string;knowledge:string;spectrumReason:string;disciplineNote:string;schoolNotes:Record<SchoolKey,string>;candidate1:string;candidate2:string;candidate3:string;comparison:string;objection:string;nextStep:string};
const initial:LabState={step:0,discipline:0,foundation:50,explain:50,method:50,crisis:'',mephReply:'',knowledge:'',spectrumReason:'',disciplineNote:'',schoolNotes:{uzh:'',zhaw:'',unilu:''},candidate1:'',candidate2:'',candidate3:'',comparison:'',objection:'',nextStep:''};
const steps=['Gelehrtenkrise','Erkenntnisprofil','Fächerstreit','Hochschulrecherche','Begründete Shortlist'];

export default function Studienwahllabor(){
 const [state,setState]=useState<LabState>(initial);const [ready,setReady]=useState(false);
 useEffect(()=>{/* eslint-disable react-hooks/set-state-in-effect -- browser-only local workspace */try{const saved=JSON.parse(localStorage.getItem('faust-studienwahl-parcours')||'{}');setState({...initial,...saved,schoolNotes:{...initial.schoolNotes,...saved.schoolNotes}});}catch{}setReady(true);/* eslint-enable react-hooks/set-state-in-effect */},[]);
 useEffect(()=>{if(ready)localStorage.setItem('faust-studienwahl-parcours',JSON.stringify(state));},[ready,state]);
 const set=<K extends keyof LabState>(key:K,value:LabState[K])=>setState(current=>({...current,[key]:value}));
 const field=(key:keyof LabState,placeholder:string,rows=4)=><textarea rows={rows} value={String(state[key])} onChange={e=>set(key,e.target.value as never)} placeholder={placeholder}/>;
 const d=disciplines[state.discipline];
 const finish=`${state.candidate1} ${state.candidate2} ${state.candidate3} ${state.comparison} ${state.objection} ${state.nextStep}`;
 return <section className="studyChoiceLab studyParcours" id="studienwahl">
  <header><div><p className="worldEyebrow">Studienwahl-Parcours · Faust I</p><h2>Was willst du<br/>wirklich wissen?</h2></div><p>Faust kennt viele Fächer und findet trotzdem keine Richtung. Dieser Parcours macht seine Gelehrtenkrise zum Prüfstein: Suchst du Erkenntnis um ihrer selbst willen, eine konkrete Wirkung – oder eine begründete Verbindung von beidem?</p></header>
  <nav className="parcoursNav" aria-label="Schritte des Studienwahl-Parcours">{steps.map((label,index)=><button key={label} className={state.step===index?'active':state.step>index?'visited':''} onClick={()=>set('step',index)}><span>{state.step>index?'✓':index+1}</span><strong>{label}</strong></button>)}</nav>
  <div className="parcoursStage">
   {state.step===0&&<div className="crisisStage"><div className="stageLead"><span>01 · 15 Minuten · Textdiagnose</span><h3>Was genau ist an Fausts Wissen gescheitert?</h3><p>Lies die drei Ausschnitte. Schreibe danach keine Zusammenfassung, sondern eine Diagnose mit Beleg.</p></div><blockquote className="faustEvidence"><p>„Habe nun, ach! Philosophie, / Juristerei und Medizin, / Und leider auch Theologie / Durchaus studiert …“</p><p>„Da steh ich nun, ich armer Tor! / Und bin so klug als wie zuvor.“</p><p>„Dass ich erkenne, was die Welt / Im Innersten zusammenhält“</p><footer>Faust I · Nacht</footer></blockquote><div className="concreteBrief"><strong>Dein Auftrag</strong><ol><li>Unterstreiche gedanklich das <b>Inventar</b>: Was hat Faust studiert?</li><li>Formuliere sein <b>Urteil</b>: Was kann dieses Wissen seiner Ansicht nach nicht?</li><li>Benenne seinen <b>Massstab</b>: Welche Art von Erkenntnis verlangt er stattdessen?</li><li>Prüfe: Ist dieser Massstab erreichbar – oder macht er jede Wissenschaft zwangsläufig ungenügend?</li></ol></div><div className="parcoursFields"><label><span>A · Diagnose mit einem Textbeleg</span>{field('crisis','Faust verfügt über … Sein Wissen scheitert für ihn daran, dass … Das zeigt die Formulierung „…“.',6)}</label><label><span>B · Mephistophelische Gegenrede</span>{field('mephReply','Mephistopheles könnte einwenden: Nicht die Wissenschaft ist gescheitert, sondern dein Anspruch …, weil …',6)}</label><label><span>C · Konsequenz für deine Studienwahl</span>{field('knowledge','Ein Studium soll mir ermöglichen … Es kann mir jedoch weder … noch … garantieren. Prüfen muss ich deshalb …',6)}</label><TextFeedback prompt="Erkläre mit einem Textbeleg, woran Fausts Wissen scheitert. Unterscheide Wissensbestand, Erkenntnisanspruch und Lebenssinn. Formuliere eine mephistophelische Gegenrede und eine konkrete Konsequenz für deine Studienwahl." answer={`${state.crisis} ${state.mephReply} ${state.knowledge}`}/></div></div>}
   {state.step===1&&<div className="profileStage"><div className="stageLead"><span>02 · 20 Minuten · Wissenschaftstheorie</span><h3>Was möchtest du erklären – und was verändern?</h3><p>Grundlagen und Anwendung sind keine Hochschuletiketten. Prüfe an konkreten Fragen, welche Arbeitsbewegung dich stärker interessiert.</p></div><div className="examplePairs"><article><span>Psychologie</span><p><b>Grundlage:</b> Wie speichert das Gedächtnis Informationen?</p><p><b>Anwendung:</b> Wie gestaltet man wirksame Lernhilfen?</p></article><article><span>Sprachwissenschaft</span><p><b>Grundlage:</b> Wie verändern sich Sprachen?</p><p><b>Anwendung:</b> Wie wird Kommunikation zugänglich?</p></article><article><span>Medizin</span><p><b>Grundlage:</b> Wie entsteht eine Erkrankung?</p><p><b>Anwendung:</b> Welche Behandlung wirkt für wen?</p></article><article><span>Recht</span><p><b>Grundlage:</b> Wie werden Normen begründet?</p><p><b>Anwendung:</b> Wie ist ein konkreter Konflikt zu entscheiden?</p></article></div><div className="spectrumBoard">{([['foundation','Grundlagen untersuchen','Anwendung entwickeln'],['explain','Erklären und verstehen','Entwerfen und verändern'],['method','Text, Begriff, Argument','Beobachtung, Daten, Experiment']] as const).map(([key,left,right])=><label key={key}><div><strong>{left}</strong><b>{state[key]}</b><strong>{right}</strong></div><input type="range" min="0" max="100" value={state[key]} onChange={e=>set(key,Number(e.target.value))}/><small>0 = ganz links · 50 = Verbindung · 100 = ganz rechts</small></label>)}<label className="wideField"><span>Formuliere dein eigenes Fragenpaar</span>{field('spectrumReason','Grundlagenfrage: Wie/warum …?\nAnwendungsfrage: Wie lässt sich …?\nMich zieht stärker … an, weil ich dabei konkret … tun würde.',6)}</label></div></div>}
   {state.step===2&&<div className="disciplineStage"><div className="stageLead"><span>03 · 25 Minuten · Tätigkeitsprobe</span><h3>Was würdest du in diesem Fach tatsächlich tun?</h3><p>Wechsle durch alle vier Fächer. Lies nicht nur die Perspektiven, sondern bearbeite mindestens eine konkrete Probeaufgabe.</p></div><div className="disciplineTabs">{disciplines.map((item,index)=><button key={item.name} className={state.discipline===index?'active':''} onClick={()=>set('discipline',index)}>{item.name}</button>)}</div><div className="disciplineQuestion"><span>Leitfrage</span><h4>{d.question}</h4><small>{d.scene}</small></div><div className="perspectiveDesk"><article className="faustView"><div className="perspectiveHead"><span>F</span><div><small>Faustische Perspektive</small><h3>Erkenntnis suchen</h3></div></div><p>{d.faust}</p></article><div className="versus">↔</div><article className="mephistoView"><div className="perspectiveHead"><span>M</span><div><small>Mephistophelische Perspektive</small><h3>Ansprüche prüfen</h3></div></div><p>{d.mephisto}</p></article></div><div className="practiceCard"><div><span>Typische Arbeitsbewegungen</span><p>{disciplinePractice[d.name].work}</p></div><div><span>10-Minuten-Probe</span><p>{disciplinePractice[d.name].sample}</p></div><ul>{disciplinePractice[d.name].check.map(item=><li key={item}>{item}</li>)}</ul></div><label className="parcoursSingle"><span>Auswertung der Probe</span>{field('disciplineNote',`Bei der Probe zu ${d.name} fiel mir leicht … Schwierig war … Die faustische Erwartung … teile ich (nicht), weil … Mephistopheles’ Einwand …`,7)}</label></div>}
   {state.step===3&&<div className="researchStage"><div className="stageLead"><span>04 · 35 Minuten · Drei Browserfenster</span><h3>Recherchiere Module statt Werbesätze.</h3><p>Wähle pro Hochschule mindestens ein Programm. Übertrage genaue Angaben aus der offiziellen Seite und notiere die URL oder den Seitentitel.</p></div><div className="researchChecklist"><span>Für jedes Programm festhalten:</span><b>1. genaue Bezeichnung</b><b>2. drei konkrete Module oder Themen</b><b>3. typische Methode oder Arbeitsform</b><b>4. Grundlagen- und Anwendungsanteil</b><b>5. Zulassung oder nächster Infotermin</b></div><div className="schoolGrid">{schools.map(school=><article key={school.key}><div><span>{school.type}</span><h4>{school.name}</h4></div><p>{school.note}</p><div className="programExamples"><span>Startpunkte aus dem Angebot</span>{schoolExamples[school.key].map(item=><b key={item}>{item}</b>)}</div><a href={school.url} target="_blank" rel="noreferrer">Offizielles Studienangebot öffnen ↗</a><label><span>Verbindliches Rechercheprotokoll</span><textarea rows={10} value={state.schoolNotes[school.key]} onChange={e=>set('schoolNotes',{...state.schoolNotes,[school.key]:e.target.value})} placeholder="Programm: …\nQuelle/Unterseite: …\n3 Module/Themen: 1. … 2. … 3. …\nTypische Methode: …\nGrundlagen 0–100: …, weil …\nAnwendung 0–100: …, weil …\nZulassung/Infotermin: …\nMeine Rückfrage: …"/></label></article>)}</div><div className="sourceNote">Die Beispiele sind Recherche-Startpunkte, keine Empfehlungen. Angebote und Zulassungsbedingungen können sich ändern; massgeblich sind die verlinkten offiziellen Seiten. Geprüft am 03.09.2026.</div></div>}
   {state.step===4&&<div className="shortlistStage"><div className="stageLead"><span>05 · 20 Minuten · Entscheidungsmatrix</span><h3>Eine Shortlist, die Widerspruch aushält.</h3><p>Übertrage nur Programme, die du in Schritt 4 tatsächlich geprüft hast. Verwende für alle drei dieselben sechs Kriterien.</p></div><div className="criteriaStrip"><span>Vergleichskriterien</span><b>Erkenntnisfrage</b><b>Arbeitsformen</b><b>Grundlagenanteil</b><b>Anwendungsbezug</b><b>Verantwortung</b><b>offene Unsicherheit</b></div><div className="candidateGrid">{(['candidate1','candidate2','candidate3'] as const).map((key,index)=><label key={key}><span>Kandidat {index+1}</span>{field(key,'Programm + Hochschule\nLeitfrage: …\nTypische Arbeit: …\nGrundlagen/Anwendung: …\nGesellschaftliche Verantwortung: …\nNoch ungeklärt: …',8)}</label>)}</div><div className="finalReasoning"><label><span>Direkter Vergleich mit Belegen</span>{field('comparison','Kandidat 1 passt methodisch besser zu mir, weil im Modul … konkret … verlangt wird. Kandidat 2 bietet mehr Anwendung durch … Kandidat 3 beantwortet meine Erkenntnisfrage …',7)}</label><label><span>Stärkster faustischer oder mephistophelischer Einwand</span>{field('objection','Faust würde an meiner ersten Wahl kritisieren … Mephistopheles würde einwenden … Der stärkere Einwand ist …, weil …',6)}</label><label><span>Nächster Schritt mit Datum</span>{field('nextStep','Bis zum TT.MM. besuche ich … / lese ich das Modulhandbuch … / frage ich die Studienberatung konkret: …',5)}</label><TextFeedback prompt="Erstelle eine begründete Shortlist aus drei recherchierten Studiengängen. Vergleiche Erkenntnisfrage, Arbeitsformen, Grundlagen, Anwendung und Verantwortung anhand konkreter Module. Beantworte einen starken Einwand und formuliere einen datierten nächsten Schritt." answer={finish}/></div></div>}
  </div>
  <footer className="parcoursControls"><button disabled={state.step===0} onClick={()=>set('step',state.step-1)}>← Zurück</button><div><span>Schritt {state.step+1} von {steps.length}</span><i><b style={{width:`${((state.step+1)/steps.length)*100}%`}}/></i></div><button disabled={state.step===steps.length-1} onClick={()=>set('step',state.step+1)}>Weiter →</button></footer>
 </section>;
}
