'use client';

import { useEffect, useState } from 'react';
import { TextFeedback } from '../feedback';
import type { DocumentAnalysis } from './documentAnalysis';

type ConferenceState={size:2|3;round:number;names:string[];contributions:string[][];replies:string[];synthesis:string;dissent:string;nextAction:string};
const initial:ConferenceState={size:2,round:0,names:['Person A','Person B','Person C'],contributions:Array.from({length:3},()=>['','','']),replies:['','',''],synthesis:'',dissent:'',nextAction:''};
const words=(value:string)=>value.trim().split(/\s+/).filter(Boolean).length;
const studentIdea=(value:string)=>value.trim()?`„${value.trim().replace(/\s+/g,' ').slice(0,190)}${value.trim().length>190?' …':''}“`:'Noch fehlt der Gedanke der Inputgeber*in.';
function faustVoice(value:string){
 if(/zweifel|unsicher|zwischen|einerseits|andererseits/i.test(value))return{quote:'„Zwei Seelen wohnen, ach! in meiner Brust.“',source:'Vor dem Tor',comment:'Dein Schwanken ist nicht bloss ein Defizit. Es zeigt zwei Ansprüche, die du noch nicht vorschnell versöhnen solltest. Benenne für beide Seiten je eine konkrete Tätigkeit im Studienalltag.'};
 if(/praxis|anwenden|menschen|helfen|wirkung|gestalten/i.test(value))return{quote:'„Im Anfang war die Tat!“',source:'Studierzimmer',comment:'Du willst Wissen an seiner Wirkung prüfen. Das ist eine Richtung, aber noch kein Studienentscheid: Welche wiederkehrende Tätigkeit möchtest du tatsächlich ausüben – untersuchen, entwerfen, beraten, behandeln oder vermitteln?'};
 if(/interesse|neugier|verstehen|forschen|frage|erkennen/i.test(value))return{quote:'„Dass ich erkenne, was die Welt / Im Innersten zusammenhält.“',source:'Nacht',comment:'In deinem Gedanken steckt echter Erkenntnisdrang. Prüfe nun seine Form: Reizt dich eher das geduldige Erklären eines Problems oder nur das grosse Thema? Nenne eine konkrete Arbeitsweise, die du gern wiederholen würdest.'};
 return{quote:'„Habe nun, ach! Philosophie, / Juristerei und Medizin, / Und leider auch Theologie!“',source:'Nacht',comment:'Viele Fächer zu kennen schafft noch keine Richtung. Dein nächster Schritt ist deshalb nicht ein weiteres Etikett, sondern eine konkrete Tätigkeit aus deinem Text oder Journal, die du im Studium häufiger erleben willst.'};
}
function mephistoVoice(value:string){
 if(!/ausschnitt|text|arbeit|journal|stelle|zeigt|beleg|weil|beispiel/i.test(value))return{quote:'„Grau, teurer Freund, ist alle Theorie, / Und grün des Lebens goldner Baum.“',source:'Studierzimmer · Schülerszene',comment:'Dein Gedanke klingt plausibel, steht aber noch ohne Boden da. Ich akzeptiere ihn erst, wenn du eine Textstelle aus Arbeit oder Journal und eine überprüfbare Alltagserfahrung danebenlegst.'};
 if(/medizin|gesund|arzt|psycholog/i.test(value))return{quote:'„Der Geist der Medizin ist leicht zu fassen.“',source:'Studierzimmer · Schülerszene',comment:'Vorsicht vor dem schönen Bild eines helfenden Berufs. Welche unangenehme Kerntätigkeit – Statistik, Dokumentation, Schichtarbeit oder lange Ausbildung – hast du bereits realistisch geprüft?'};
 if(/recht|jura|gesetz/i.test(value))return{quote:'„Es erben sich Gesetz’ und Rechte / Wie eine ew’ge Krankheit fort.“',source:'Studierzimmer · Schülerszene',comment:'Du darfst die Disziplin nicht mit ihrem gesellschaftlichen Anspruch verwechseln. Welche konkrete Fallarbeit oder Methode trägt dein Interesse auch dann, wenn Prestige und Titel wegfallen?'};
 if(/theolog|sprache|literatur|philosoph|geschichte/i.test(value))return{quote:'„Mit Worten lässt sich trefflich streiten.“',source:'Studierzimmer · Schülerszene',comment:'Starke Worte können fehlende Prüfung verdecken. Welche Behauptung deines Beitrags könnte jemand mit einem Gegenbeleg angreifen – und was müsste dich dann umstimmen?'};
 return{quote:'„Ich bin der Geist, der stets verneint!“',source:'Studierzimmer',comment:'Ich prüfe deine Schlussfolgerung gegen den Strich: Folgt der Studienwunsch wirklich aus deinem Beleg, oder erzählst du im Rückblick eine zu glatte Geschichte? Formuliere die stärkste alternative Deutung.'};
}

export default function StudyChoiceConference({work,journal}:{work:DocumentAnalysis|null;journal:DocumentAnalysis|null}){
 const [state,setState]=useState(initial);const [ready,setReady]=useState(false);
 useEffect(()=>{/* eslint-disable react-hooks/set-state-in-effect -- local collaborative workspace */try{const saved=JSON.parse(localStorage.getItem('faust-studienwahl-konferenz')||'{}');setState({...initial,...saved,names:[...initial.names,...(saved.names||[])].slice(0,3),contributions:initial.contributions.map((row,index)=>[...row,...(saved.contributions?.[index]||[])].slice(0,3)),replies:[...initial.replies,...(saved.replies||[])].slice(0,3)});}catch{}setReady(true);/* eslint-enable react-hooks/set-state-in-effect */},[]);
 useEffect(()=>{if(ready)localStorage.setItem('faust-studienwahl-konferenz',JSON.stringify(state));},[ready,state]);
 const update=(patch:Partial<ConferenceState>)=>setState(current=>({...current,...patch}));
 const setSize=(size:2|3)=>update({size,round:Math.min(state.round,size-1)});
 const setName=(index:number,value:string)=>{const names=[...state.names];names[index]=value;update({names});};
 const setContribution=(round:number,index:number,value:string)=>{const contributions=state.contributions.map(row=>[...row]);contributions[round][index]=value;update({contributions});};
 const current=state.contributions[state.round].slice(0,state.size);const focus=state.round;
 const workSignal=work?[...work.signals].sort((a,b)=>b.score-a.score)[0]:null;const journalSignal=journal?[...journal.signals].sort((a,b)=>b.score-a.score)[0]:null;
 const role=(index:number)=>{const offset=(index-focus+state.size)%state.size;if(offset===0)return{label:'Inputgeber*in',prompt:'Stelle einen Befund mit einer kurzen Belegstelle vor. Erkläre, was er für deine Studienwahl bedeuten könnte.'};if(state.size===2)return{label:'Kritisches Gegenüber',prompt:'Spiegle den Befund fair. Nenne danach eine Chance, einen Einwand und eine konkrete Rückfrage.'};if(offset===1)return{label:'Faust-Perspektive',prompt:'Welche Erkenntnischance und welches Entwicklungspotenzial stecken in diesem Profil? Begründe am Dokument.'};return{label:'Mephisto-Perspektive',prompt:'Welche Selbsttäuschung, Übertreibung oder Lücke könnte darin stecken? Formuliere einen prüfbaren Einwand.'};};
 const setReply=(value:string)=>{const replies=[...state.replies];replies[state.round]=value;update({replies});};
 const allContributed=current.every(value=>words(value)>=25);const hasEvidence=current.some(value=>/ausschnitt|text|arbeit|journal|stelle|zeigt|beleg/i.test(value));const roundText=`${current.join(' ')} ${state.replies[state.round]}`;const faust=faustVoice(current[focus]);const mephisto=mephistoVoice(roundText);
 const finalText=`${state.synthesis} ${state.dissent} ${state.nextAction}`;
 return <section className="choiceConference" aria-labelledby="conference-title">
  <header><div><span>Interaktive Studienwahl-Konferenz</span><h3 id="conference-title">Nicht beraten lassen.<br/>Gemeinsam genauer werden.</h3></div><p>Arbeitet zu zweit oder zu dritt an einem Gerät. Jede Person bringt einen Befund ein, erhält eine ermutigende und eine kritische Rückmeldung und muss am Ende selbst entscheiden, was sie daraus übernimmt.</p></header>
  <div className="conferenceSetup"><div className="groupMode" aria-label="Gruppengrösse"><button className={state.size===2?'active':''} onClick={()=>setSize(2)}>Partnerarbeit · 2</button><button className={state.size===3?'active':''} onClick={()=>setSize(3)}>Dreiergruppe · 3</button></div><div className="participantNames">{Array.from({length:state.size},(_,index)=><label key={index}><span>Teilnehmer*in {index+1}</span><input value={state.names[index]} onChange={event=>setName(index,event.target.value)} aria-label={`Name oder Kürzel von Teilnehmer*in ${index+1}`}/></label>)}</div></div>
  <div className="conferenceMaterial"><span>Startmaterial aus euren Uploads</span>{workSignal?<article><b>Maturarbeit</b><p>{workSignal.label}: <strong>{workSignal.level}</strong></p></article>:<article className="missing"><b>Maturarbeit</b><p>Noch nicht hochgeladen – bringt stattdessen einen selbst gewählten Textbeleg ein.</p></article>}{journalSignal?<article><b>Arbeitsjournal</b><p>{journalSignal.label}: <strong>{journalSignal.level}</strong></p></article>:<article className="missing"><b>Arbeitsjournal</b><p>Noch nicht hochgeladen – bringt stattdessen eine konkrete Prozesssituation ein.</p></article>}</div>
  <nav className="roundNav" aria-label="Gesprächsrunden">{Array.from({length:state.size},(_,index)=><button key={index} className={state.round===index?'active':''} onClick={()=>update({round:index})}><span>{index+1}</span><b>{state.names[index]||`Person ${index+1}`} im Fokus</b></button>)}</nav>
  <section className="conferenceRound"><header><div><span>Runde {state.round+1} · 12 Minuten</span><h4>{state.names[focus]||`Person ${focus+1}`} bringt eine Forschungsspur ein.</h4></div><div className={`roundReadiness ${allContributed&&hasEvidence?'ready':''}`}><b>{allContributed&&hasEvidence?'Runde auswertbar':'Noch in Arbeit'}</b><span>{current.filter(value=>words(value)>=25).length}/{state.size} Beiträge · {hasEvidence?'Beleg vorhanden':'Beleg fehlt'}</span></div></header><div className={`roleGrid size${state.size}`}>{Array.from({length:state.size},(_,index)=>{const assigned=role(index);return <article className={index===focus?'focusRole':''} key={index}><div><span>{assigned.label}</span><b>{state.names[index]||`Person ${index+1}`}</b></div><p>{assigned.prompt}</p><textarea rows={8} value={state.contributions[state.round][index]} onChange={event=>setContribution(state.round,index,event.target.value)} placeholder={index===focus?'Mein Befund lautet … Im Dokument steht … Das könnte für meine Studienwahl bedeuten …':'Ich habe verstanden, dass … Ein konkreter Beleg dafür ist … Meine Rückfrage / mein Einwand lautet …'}/><small>{words(state.contributions[state.round][index])} Wörter · Ziel: mindestens 25</small></article>;})}</div><section className="faustDialogue" aria-live="polite"><header><span>Textdialog · Faust I</span><h5>Faust und Mephisto antworten auf euren Gedanken</h5><blockquote>{studentIdea(current[focus])}<footer>{state.names[focus]||`Person ${focus+1}`}</footer></blockquote></header><div className="dialogueVoices"><article className="faustSpeech"><div><b>Faust</b><span>sucht Möglichkeit</span></div><blockquote>{faust.quote}<footer>Faust I · {faust.source}</footer></blockquote><p>{faust.comment}</p></article><article className="mephistoSpeech"><div><b>Mephisto</b><span>prüft den blinden Fleck</span></div><blockquote>{mephisto.quote}<footer>Faust I · {mephisto.source}</footer></blockquote><p>{mephisto.comment}</p></article></div><label><span>Eure Antwort an beide</span><textarea rows={5} value={state.replies[state.round]} onChange={event=>setReply(event.target.value)} placeholder="Faust hilft uns zu sehen, dass … Mephistos Einwand trifft / verfehlt unseren Gedanken, weil im Text oder Journal … Deshalb präzisieren wir …"/><small>Übernehmt nicht einfach das Urteil. Widersprecht mit einem Beleg, wenn es euren Gedanken verfehlt.</small></label></section><TextFeedback mode="group" prompt="Führt eine Studienwahldiskussion mit einem belegten Input, fairer Spiegelung und einer eigenen Antwort auf Fausts Möglichkeit sowie Mephistos Einwand. Begründet Zustimmung oder Widerspruch mit dem Text oder Arbeitsjournal." answer={roundText}/><div className="roundControls"><button onClick={()=>update({round:(state.round-1+state.size)%state.size})}>← Vorherige Person</button><p>Wechselt den Fokus, bis jede Person Inputgeber*in war.</p><button onClick={()=>update({round:(state.round+1)%state.size})}>Fokus weitergeben →</button></div></section>
  <section className="conferenceDecision"><header><span>Gemeinsamer Abschluss · 12 Minuten</span><h4>Konsens ist erlaubt. Begründeter Dissens auch.</h4></header><div><label><span>Was sehen alle ähnlich?</span><textarea rows={6} value={state.synthesis} onChange={event=>update({synthesis:event.target.value})} placeholder="In Arbeit und Journal wird sichtbar … Für die Studienwahl spricht deshalb … Der konkrete Beleg ist …"/></label><label><span>Wo bleibt ein begründeter Widerspruch?</span><textarea rows={6} value={state.dissent} onChange={event=>update({dissent:event.target.value})} placeholder="Wir sind uns nicht einig, ob … Person … meint …, weil … Person … hält dagegen …"/></label><label><span>Wer tut was bis wann?</span><textarea rows={6} value={state.nextAction} onChange={event=>update({nextAction:event.target.value})} placeholder="Person A prüft bis … den Studiengang … anhand des Moduls … Person B besucht … Person C fragt die Studienberatung …"/></label></div><TextFeedback mode="group" prompt="Formuliert einen belegten Konsens, einen sichtbaren Dissens und für jede Person einen konkreten nächsten Studienwahlschritt mit Termin." answer={finalText}/></section>
 </section>;
}
