'use client';

import { useState } from 'react';
import { TextFeedback } from '../feedback';
import type { Task } from './data';
import VoiceCapture from './VoiceCapture';

type Mission={scene:string;quote:string;hook:string;action:string;twist:string;lookFor:string;verdict:string};
const missions:Record<string,Mission>={
  'w-self':{scene:'Nacht · Erkenntnisbox',quote:'„Dass wir nichts wissen können!“',hook:'Nimm eine Behauptung, die heute im Unterricht oder in deinem Feed auftauchte und die überprüfbar ist.',action:'Lege einen Gegenstand als Marker auf eine Linie von 0 bis 100 Prozent Gewissheit. Sprich 30 Sekunden lang nur aus, worauf deine Sicherheit tatsächlich beruht.',twist:'Entferne deine stärkste Quelle gedanklich. Verschiebe den Marker. Nicht „unsicherer“ genügt: Sage, welcher Teil deines Wissens wegfällt.',lookFor:'Wo machst du wie Faust aus einer Grenze deiner Quelle eine zu grosse Aussage über das Ganze?',verdict:'Was weisst du weiterhin, was vermutest du nur und welche zusätzliche Methode könnte die Lücke verkleinern?'},
  'w-pair':{scene:'Nacht · Eingangsmonolog',quote:'„Habe nun, ach! … durchaus studiert … / Und sehe, dass wir nichts wissen können!“',hook:'Legt vier Zettel zwischen euch: STUDIERT – TOR – WIE ZUVOR – NICHTS WISSEN.',action:'Person A liest die Satzfolge laut. Person B schiebt bei jedem Sprung einen Gegenstand weiter weg: vom belegbaren Befund zum Totalurteil.',twist:'Tauscht die Rollen. Person B muss Faust so stark wie möglich verteidigen; Person A darf nur mit einem exakten Wort aus dem Monolog widersprechen.',lookFor:'An welcher sprachlichen Stelle wird aus Fausts Erfahrung eine Behauptung über „wir“?',verdict:'Welche Bilanz darf Faust ziehen – und welche reicht weiter, als seine Gründe tragen?'},
  'w-trio':{scene:'Nacht · Faust, Wagner, Jury',quote:'„Zwar weiss ich viel, doch möcht’ ich alles wissen.“',hook:'Eine Person ist Faust, eine Wagner, eine unentschiedene Jury. Keine vorbereiteten Dialoge.',action:'Faust hat 40 Sekunden für die Anklage gegen sein Studium. Wagner antwortet 40 Sekunden. Beide müssen je ein Originalwort auf einen Zettel schreiben und hochhalten.',twist:'Die Jury streicht beiden das stärkste Argument. Beide müssen ihre Position mit dem verbleibenden Material neu aufbauen.',lookFor:'Welche Position hält eine Gegenprobe aus, ohne ihre eigene Grenze zu verstecken?',verdict:'Formuliert ein Urteil, das Fausts Krise ernst nimmt, ohne aus begrenztem Wissen Nichtwissen zu machen.'},
  'k-self':{scene:'Nacht · Wissen und Brauchen',quote:'„Was man nicht weiss, das eben brauchte man, / Und was man weiss, kann man nicht brauchen.“',hook:'Erinnere dich an eine harmlose Schulentscheidung, bei der du alle Fakten hattest und trotzdem nicht wusstest, was du tun sollst.',action:'Lege drei Gegenstände vor dich: FAKT – WERT – ENTSCHEIDUNG. Erzähle den Fall und berühre jeweils nur den Gegenstand, zu dem dein Satz gehört.',twist:'Nimm den Wert-Gegenstand weg. Kann aus den Fakten allein noch dieselbe Entscheidung folgen?',lookFor:'Faust vermischt Erkenntnis, Brauchbarkeit und Lebenssinn. Passiert das in deinem Fall ebenfalls?',verdict:'Was konnte Wissen leisten – und welche normative Entscheidung konnte es dir nicht abnehmen?'},
  'k-pair':{scene:'Nacht · Faust trifft Wagner',quote:'„Wenn ihr’s nicht fühlt, ihr werdet’s nicht erjagen.“',hook:'Legt eure Pendelaufnahme bereit. Sie ist derselbe Gegenstand für zwei Erkenntnisideale.',action:'Eine Person sieht den Film ohne Ton und verteidigt Messung und Wiederholung. Die andere hört nur die Vorhersagen und verteidigt Erfahrung und Beteiligung.',twist:'Tauscht die Zugänge. Jede Person muss nun die Schwäche der eigenen ersten Position benennen.',lookFor:'Welche Information existiert nur in der Messspur, welche nur in der Erfahrung – und welche ist bloss Deutung?',verdict:'Wie müssen Fausts Beteiligung und Wagners Methode zusammenarbeiten, damit eine Aussage verlässlich wird?'},
  'k-trio':{scene:'Nacht · Methoden-Stresstest',quote:'„Die Kunst ist lang; / Und kurz ist unser Leben.“',hook:'Wählt eine konkrete Aussage aus Mathematik, Naturwissenschaft oder Geschichte, die ihr diese Woche verwendet habt.',action:'Person 1 nennt das Modell, Person 2 eine mögliche Beobachtung, Person 3 eine Quelle. Baut daraus in 90 Sekunden eine Prüfstrategie.',twist:'Zieht eine Störung: Messgerät ungenau, Quelle parteiisch oder Modell zu einfach. Repariert die Strategie, ohne die Aussage nur umzuschreiben.',lookFor:'Was würde Wagner dokumentieren? An welchem Punkt würde Faust fragen, ob die Methode das Wesentliche verfehlt?',verdict:'Nennt eine belastbare Methodenregel und genau den Fall, in dem sie nicht genügt.'},
  'n-self':{scene:'Nacht · Zeichen des Makrokosmos',quote:'„Welch Schauspiel! aber ach! ein Schauspiel nur!“',hook:'Wähle einen Gegenstand in Reichweite und fotografiere ihn so, dass ein wichtiges Merkmal unsichtbar bleibt.',action:'Beschreibe das Foto 30 Sekunden ohne „ist“, „wirkt“, „weil“ oder „bedeutet“. Nur Farbe, Kontur, Lage, Licht und hörbare Details sind erlaubt.',twist:'Zeige nun den Gegenstand. Nenne die erste Annahme, die das Foto nahelegte, aber nicht belegen konnte.',lookFor:'Wann ist ein begrenztes Bild brauchbar, und wann wird es mit dem Gegenstand selbst verwechselt?',verdict:'Erkläre Fausts „Schauspiel nur“ mithilfe eines sichtbaren und eines fehlenden Merkmals deines Fotos.'},
  'n-pair':{scene:'Nacht · Perspektive und Messung',quote:'„Du gleichst dem Geist, den du begreifst, / Nicht mir!“',hook:'Nehmt denselben Papierkörper. Eine Person darf nur schauen, die andere nur Länge, Gewicht oder Zeit messen.',action:'Beide geben unabhängig eine 30-sekündige Beschreibung ab. Legt die beiden Aussagen danach nebeneinander, ohne sie sofort zu vereinen.',twist:'Jede Person muss jetzt nennen, was nur die Methode der anderen sichtbar machte.',lookFor:'Welche Grenze liegt im Gegenstand – und welche in eurem Zugang zu ihm?',verdict:'Welche gemeinsame Aussage tragen beide Verfahren, und was bleibt selbst danach unbegriffen?'},
  'n-trio':{scene:'Nacht · Ein Modell vor dem Erdgeist',quote:'„Du gleichst dem Geist, den du begreifst“',hook:'Holt ein Modell aus dem Unterricht: Karte, Zellbild, Formel, Zeitleiste oder Diagramm.',action:'Person 1 zeigt, was das Modell sichtbar macht. Person 2 verdeckt einen Teil, den es auslässt. Person 3 erfindet einen Fall, bei dem genau diese Auslassung entscheidend wird.',twist:'Verändert am Modell nur ein Element. Wird es genauer – oder nur komplizierter?',lookFor:'Faust verwechselt zeitweise das Zeichen des Ganzen mit Zugang zum Ganzen. Wo droht das bei eurem Modell?',verdict:'Wofür ist das Modell stark, wo führt es in die Irre und welche Ergänzung verbessert es wirklich?'},
  'p-self':{scene:'Marthens Garten · drei Lesarten',quote:'„Gefühl ist alles; / Name ist Schall und Rauch“',hook:'Lege drei Marker vor dich: BEKENNTNIS – SPINOZISTISCHE UMDEUTUNG – AUSWEICHEN.',action:'Lies Fausts Antwort dreimal laut. Verschiebe nach jedem Satz einen Marker näher zu dir, sobald der Wortlaut diese Lesart stärkt. Nenne das auslösende Wort.',twist:'Lies danach nur Gretchens kurze Reaktionen. Darfst du deine stärkste Lesart behalten, oder zwingt ihr „Du hast kein Christentum“ zur Korrektur?',lookFor:'Wo spricht Faust über Gott – und wo spricht er darüber, warum niemand Gott eindeutig benennen könne?',verdict:'Welche Lesart trägt am stärksten, welche bleibt möglich und was lässt der Text über Fausts Aufrichtigkeit offen?'},
  'p-pair':{scene:'Marthens Garten · Frage und Credo',quote:'„Nun sag, wie hast du’s mit der Religion?“',hook:'Setzt euch einander gegenüber. Eine Person liest nur Gretchen, die andere nur Faust. Legt für jede unbeantwortete Teilfrage einen Gegenstand zwischen euch.',action:'Gretchen stoppt nach jeder Antwort und nennt ihre ursprüngliche Frage erneut: Kirche? Sakramente? Gott? Lebensführung? Faust darf nur mit seinem tatsächlichen nächsten Satz antworten.',twist:'Tauscht die Rollen. Die neue Faust-Stimme muss nach jedem Satz sagen: metaphysische Überzeugung, emotionale Erinnerung oder Beziehungsstrategie?',lookFor:'Fausts Rede kann philosophisch ernst und kommunikativ taktisch zugleich sein. Welche Ebene belegt ihr – welche vermutet ihr?',verdict:'Formuliert zwei getrennte Urteile: Was glaubt Faust wahrscheinlich, und beantwortet er Gretchen fair?'},
  'p-trio':{scene:'Marthens Garten → Kerker · metaphysisches Tribunal',quote:'„Sie ist gerichtet!“ / „Ist gerettet!“',hook:'Drei Plätze: Gretchen, spinozistische Lesart, Fausts Beziehungsinteresse. Jede Person erhält dieselben Verse aus „Marthens Garten“.',action:'Jede Stimme hat 45 Sekunden und muss genau einen Vers als Beleg sichtbar hochhalten. Danach stellt ihr euch gegenseitig je eine Frage, die eure eigene Position gefährden könnte.',twist:'Legt die beiden Schlussstimmen aus dem Kerker in die Mitte. Entscheidet grammatisch zuerst, wer „gerichtet“ und „gerettet“ wird. Erst danach dürft ihr metaphysisch deuten.',lookFor:'In Faust I wird Gretchen gerettet, nicht Faust. Verändert das eure Bewertung ihrer religiösen Klarheit und seiner Flucht?',verdict:'Wo endet Fausts Philosophie, wo beginnt sein Ausweichen – und wessen Urteil bestätigt die Stimme von oben am Schluss von Faust I?'},
  'h-self':{scene:'Prolog im Himmel · Irrtum',quote:'„Es irrt der Mensch, solang er strebt.“',hook:'Wähle eine harmlose Situation, in der du einen guten Grund kanntest und trotzdem anders gehandelt hast.',action:'Nimm zwei kurze Sprachnotizen auf: zuerst die Erklärung, die du damals gegeben hättest; dann deine Erklärung heute.',twist:'Höre beide direkt hintereinander. Markiere ein Wort, das erst im Rückblick vernünftig klingt.',lookFor:'Ist deine zweite Erklärung Erkenntnis – oder eine nachträgliche Rettung des eigenen Bildes?',verdict:'Was war Impuls, was Grund, und woran wäre zu erkennen, dass aus dem Irrtum wirklich Lernen wurde?'},
  'h-pair':{scene:'Prolog im Himmel · Wette',quote:'„Er nennt’s Vernunft und braucht’s allein, / Nur tierischer als jedes Tier zu sein.“',hook:'Spielt eure Wurfaufnahme stumm ab. Eine Person kommentiert live als Herr, die andere als Mephisto.',action:'Beide dürfen nur beschreiben, was im Körper und in der Entscheidung sichtbar ist. Danach nennt jede Stimme ihre Deutung.',twist:'Ton einschalten. Wenn die nachträgliche Begründung nicht zur sichtbaren Situation passt, müssen beide ihre Position korrigieren.',lookFor:'Welche Beobachtung trägt wirklich ein Menschenbild – und welche wird nur passend gemacht?',verdict:'Formuliert die stärkste Version beider Positionen und eine Szene aus Faust I, die zwischen ihnen noch nicht entscheidet.'},
  'h-trio':{scene:'Prolog im Himmel · Hypothesenraum',quote:'„Ein guter Mensch in seinem dunkeln Drange / Ist sich des rechten Weges wohl bewusst.“',hook:'Schreibt die Wette nicht nach. Baut sie als riskante Vorhersage über Faust auf.',action:'Person 1 nennt ein späteres Verhalten, das den Herrn stützen würde. Person 2 nennt eines für Mephisto. Person 3 entscheidet, ob beide Beobachtungen überhaupt vergleichbar sind.',twist:'Die Jury erklärt eine Beobachtung für mehrdeutig. Ersetzt sie durch ein Ereignis, das die jeweilige Position tatsächlich gefährden würde.',lookFor:'Eine Behauptung wird nur prüfbar, wenn auch klar ist, was gegen sie sprechen könnte.',verdict:'Was würde jede Seite bestätigen, was widerlegen – und warum bleibt ein einzelner Fehltritt unzureichend?'},
  'f-self':{scene:'Studierzimmer II · Entscheidung',quote:'„Werd’ ich zum Augenblicke sagen: / Verweile doch!“',hook:'Lege dein Smartphone sichtbar hin und schalte eine Benachrichtigung ein oder simuliere sie. Nimm dir zugleich eine kleine, klare Aufgabe vor.',action:'Beobachte 60 Sekunden: Blick, Handbewegung, Impuls und Entscheidung. Filme nur Hände und Tisch, wenn du die Spur später prüfen willst.',twist:'Lege das Smartphone ausser Reichweite und wiederhole. Was hat sich verändert, obwohl niemand dich gezwungen hat?',lookFor:'Einfluss und Zwang sind nicht dasselbe. Entscheidend sind verfügbare Alternativen und bemerkte Folgen.',verdict:'Welche Wahl war freier – und welches Kriterium daraus lässt sich auf Fausts Pakt anwenden?'},
  'f-pair':{scene:'Studierzimmer II · Pakt',quote:'„Blut ist ein ganz besondrer Saft.“',hook:'Legt den Pakttext zwischen euch. Eine Person markiert nur Fausts eigene Verben, die andere nur Mephistos Bedingungen und Inszenierungen.',action:'Lest die farbigen Spuren getrennt laut. Danach stellt jede Person Fausts Handlungsspielraum auf einer Linie von 0 bis 100 dar.',twist:'Tauscht die Markierungen und verschiebt eure Position nur, wenn ein konkretes Verb euch dazu zwingt.',lookFor:'Wo entscheidet Faust, wo wird sein Blick gelenkt und wo bleibt eine Alternative sichtbar?',verdict:'Gebt kein Mittelmass-Urteil ab: Nennt den stärksten Beleg für Selbstverantwortung und den stärksten für eingeschränkte Urteilsfähigkeit.'},
  'f-trio':{scene:'Gretchentragödie · Perspektivenwechsel',quote:'„Heinrich! Mir graut’s vor dir.“',hook:'Wählt eine Station: Schmuck, Garten, Schlaftrunk, Dom oder Kerker. Legt drei Gegenstände für Möglichkeit, Wissen und Macht hin.',action:'Eine Person verfolgt Fausts Entscheidungen, eine Mephistos Eingriffe, eine Gretchens tatsächliche Handlungslage. Jede verschiebt nur ihre drei Gegenstände.',twist:'Hört Gretchens Stimme oder lest ihre Rede zuletzt. Korrigiert jede Bewertung, die ihre Lage bloss aus Fausts Perspektive beschrieben hat.',lookFor:'Verantwortung kann verteilt sein, ohne erlittene Gewalt der betroffenen Person anzulasten.',verdict:'Wer konnte was wissen, anders tun und vorhersehen? Haltet einen begründeten Dissens fest, statt künstlichen Konsens zu produzieren.'}
};

export default function TaskArena({task,note,onNote}:{task:Task;note:string;onNote:(value:string)=>void}){
  const mission=missions[task.id];
  const [phase,setPhase]=useState(0);
  const count=task.form==='Selbst'?1:task.form==='Tandem'?2:3;
  const [voices,setVoices]=useState<string[]>(Array(count).fill(''));
  const phases=[['JETZT TUN',mission.action],['GEGENPROBE',mission.twist],['AM TEXT SCHÄRFEN',mission.lookFor]];
  return <div className="taskArena">
    <section className="missionOpening"><div><span>{mission.scene}</span><blockquote>{mission.quote}</blockquote></div><p>{mission.hook}</p></section>
    <nav className="missionPhases" aria-label="Ablauf der Untersuchung">{phases.map(([label],index)=><button className={phase===index?'active':''} onClick={()=>setPhase(index)} key={label}><b>0{index+1}</b><span>{label}</span></button>)}</nav>
    <section className="liveMission" key={phase}><span>{phases[phase][0]}</span><p>{phases[phase][1]}</p><div className="missionPulse" aria-hidden="true"><i/><i/><i/><i/><i/></div></section>
    <section className={`voiceRound size${count}`}><header><span>ONE TAKE · NICHT VORFORMULIEREN</span><h3>{count===1?'Deine Beobachtung in 40 Sekunden':`${count} Stimmen, je 40 Sekunden`}</h3><p>Erst sprechen, dann das Transkript gemeinsam am Wortlaut prüfen. Persönliche Beispiele dürfen ungenannt bleiben.</p></header><div>{voices.map((voice,index)=><VoiceCapture key={index} value={voice} onChange={value=>setVoices(current=>current.map((entry,i)=>i===index?value:entry))} label={count===1?'Spontane Deutung':`Stimme ${index+1}`} prompt={index===0?'Was hast du konkret gesehen, gehört oder getan?':index===1?'Was übersieht oder übertreibt die erste Deutung?':'Wo bleibt nach beiden Positionen echter Dissens?'} seconds={40} kind="text"/>)}</div></section>
    <section className="verdictBooth"><header><span>LETZTER SCHNITT</span><h3>{mission.verdict}</h3></header><VoiceCapture value={note} onChange={onNote} label={task.form==='Selbst'?'Dein Schluss':'Euer gemeinsamer Schluss'} prompt="Sprecht frei. Nennt eine Beobachtung aus der Aktion, ein kurzes Textsignal und eine Grenze eures Urteils." seconds={60} kind="text"/><TextFeedback prompt={`${task.prompt} ${mission.verdict}`} answer={note} mode={task.form==='Selbst'?'reflection':'group'}/></section>
  </div>;
}
